---
name: Hugo workflow
on:   # yamllint disable-line rule:truthy
  push:
    schedule:
    - cron: '0 0 * * *'   # runs every day at 00:00
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Execute validation
          run: Make lint && Make build && Make tests
