---
name: module3_task1
on:   # yamllint disable-line rule:truthy
  push:
  schedule:
    - cron: '0 0 * * *'   # runs every day at 00:00

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ''
      - name: run setup.sh
        run: ./module3_task1/setup.sh
      - name: Display help
        run: cd module3_task1/ && make help
      - name: build
        run: cd module3_task1/ && make build
      - name: run
        run: cd module3_task1/ && make run
      - name: post
        run: cd module3_task1/ && make \
             POST_NAME=who-are-we POST_TITLE="Who are we" post
      - name: clean
        run: cd module3_task1/ && make clean

  prod-checks:
    runs-on: ubuntu-22.04
    steps: 
      - id: checkout
        uses: actions/checkout@v3
        with:
          repository: ''
      - name: tests
        id: pass_test
        run: cd module3_task2/ && make test
      - name: zip package if pass 
        run: if [[ ${{ steps.pass_test.result }} == "ok"]]; then make package; fi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        run: git add 
        with: 
          name: awesome-website.zip
          path: ./module3_task2