---
name: module3_task1
on:   # yamllint disable-line rule:truthy
  push:
  schedule:
    - cron: '0 0 * * *'   # runs every day at 00:00

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ''

      - name: run setup.sh
        run: ./module3_task1/setup.sh
      - name: Display help
        run: cd module3_task1/ && make help
      - name: build
        run: cd module3_task1/ && make build
      - name: post
        run: cd module3_task1/ && make post
      - name: validate
        run: cd module3_task1/ && make validate
      - name: Clean
        run: cd module3_task1/ && make clean
