---
name: module3_task3
on:   # yamllint disable-line rule:truthy
  push:
  schedule:
    - cron: '0 0 * * *'   # runs every day at 00:00

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ''
      - name: run setup.sh
        run: ./module3_task2/setup.sh
      - name: build
        run: cd module3_task2/ && make build
      - name: run
        run: cd module3_task2/ && make run
      - name: unit-tests
        run: |
          cd module3_task2/ && go mod init module3_task2 \
          && go get github.com/gorilla/mux && make unit-tests
      - name: integration-tests
        run: |
          cd module3_task2/ \
          && go get github.com/gorilla/mux && make integration-tests
      - name: lint
        run: cd module3_task2/ && make lint
      - name: validate
        run: cd module3_task2/ && make validate
      - name: zip package
        run: cd module3_task2/ && make package
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
      - name: Build
        run: cat ./DEPLOY.md >> Release.txt

  prod-checks:
    runs-on: ubuntu-22.04
    steps: 
      - id: checkout
        uses: actions/checkout@v3
        with:
          repository: ''
      - name: tests
        id: pass_test
        run: |
          cd module3_task2/ && go mod init module3_task2
          go get github.com/gorilla/mux && make test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3 
        with: 
          name: package-zip
          path: module3_task2/awesome-website.zip