---
name: module3_task4
on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - "1.0.1"
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 0 * * *'   # Runs Everyday at 00:00

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ''
      - name: run setup.sh
        run: ./module3_task4/setup.sh
      - name: build
        run: cd module3_task4/ && make build
      - name: run
        run: cd module3_task4/ && make run
      - name: unit-tests
        run: |
          cd module3_task4/ && go mod init module3_task4 \
          && go get github.com/gorilla/mux && make unit-tests
      - name: integration-tests
        run: |
          cd module3_task4/ \
          && go get github.com/gorilla/mux && make integration-tests
      - name: lint
        run: cd module3_task4/ && make lint
      - name: validate
        run: cd module3_task4/ && make validate
      - name: zip package
        run: cd module3_task4/ && make package
      - name: tests
        id: pass_test
        run: cd module3_task4/ && make test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package-zip
          path: module3_task4/awesome-website.zip
      - name: add content
        run: cat ./module3_task4/DEPLOY.md >> Release.txt
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.1')
        with:
          files: |
            Release.txt
            awesome-website.zip
            DEPLOY.md
          body: |
            ## What is in the archive and how to unarchive it?
            ## What are the commands to start and stop the application?
            ## How to customize where the application logs are written?
            ## How to “quickly” verify that the application is running?
            ## How to create a release with the archive triggered by a tag?
