---
name: module3_task2
on:   # yamllint disable-line rule:truthy
  push:
  schedule:
    - cron: '0 0 * * *'   # runs every day at 00:00

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ''
      - name: run setup.sh
        run: ./module3_task2/setup.sh
      - name: Display help
        run: cd module3_task2/ && make help
      - name: build
        run: cd module3_task2/ && make build
      - name: run
        run: cd module3_task2/ && make run
      - name: post
        run: cd module3_task2/ && make \
             POST_NAME=who-are-we POST_TITLE="Who are we" post
      - name: clean
        run: cd module3_task2/ && make clean

  prod-checks:
    runs-on: ubuntu-22.04
    steps: 
      - id: checkout
        uses: actions/checkout@v3
        with:
          repository: ''
      - name: tests
        id: pass_test
        run: |
          cd module3_task2/ && go mod init module3_task2
          go get github.com/gorilla/mux && make test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3 
        with: 
          name: package-zip
          path: module3_task2/awesome-website.zip